---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: flake8
  image: python:3.8
  commands:
  - pip install pipenv -qq
  - pipenv --bare install --dev --keep-outdated
  - pipenv run flake8 ./dockertidy
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: dependencies

platform:
  os: linux
  arch: amd64

steps:
- name: pipenv
  image: python:3.8
  commands:
  - pip install pipenv -qq
  - pipenv --bare install --keep-outdated
  - pipenv --bare install --dev --keep-outdated
  - pipenv run pipenv-setup check
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- lint

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: python35-pytest
  image: python:3.5
  commands:
  - pip install pipenv -qq
  - pipenv --bare install --dev --keep-outdated
  - pipenv run pytest dockertidy --cov=dockertidy --no-cov-on-fail
  - pip install -qq .
  - docker-tidy --help
  - docker-tidy --version
  environment:
    PY_COLORS: 1
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}
  depends_on:
  - clone

- name: python36-pytest
  image: python:3.6
  commands:
  - pip install pipenv -qq
  - pipenv --bare install --dev --keep-outdated
  - pipenv run pytest dockertidy --cov=dockertidy --no-cov-on-fail
  - pip install -qq .
  - docker-tidy --help
  - docker-tidy --version
  environment:
    PY_COLORS: 1
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}
  depends_on:
  - clone

- name: python37-pytest
  image: python:3.7
  commands:
  - pip install pipenv -qq
  - pipenv --bare install --dev --keep-outdated
  - pipenv run pytest dockertidy --cov=dockertidy --no-cov-on-fail
  - pip install -qq .
  - docker-tidy --help
  - docker-tidy --version
  environment:
    PY_COLORS: 1
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}
  depends_on:
  - clone

- name: python38-pytest
  image: python:3.8
  commands:
  - pip install pipenv -qq
  - pipenv --bare install --dev --keep-outdated
  - pipenv run pytest dockertidy --cov=dockertidy --no-cov-on-fail
  - pip install -qq .
  - docker-tidy --help
  - docker-tidy --version
  environment:
    PY_COLORS: 1
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}
  depends_on:
  - clone

- name: codecov
  image: python:3.8
  commands:
  - pip install codecov -qq
  - codecov --required -X gcov
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
    PY_COLORS: 1
  depends_on:
  - python35-pytest
  - python36-pytest
  - python37-pytest
  - python38-pytest

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- dependencies

---
kind: pipeline
name: security

platform:
  os: linux
  arch: amd64

steps:
- name: bandit
  image: python:3.8
  commands:
  - pip install pipenv -qq
  - pipenv --bare install --dev --keep-outdated
  - pipenv run bandit -r ./dockertidy -x ./dockertidy/test
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.8
  commands:
  - python setup.py sdist bdist_wheel
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: checksum
  image: alpine
  commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

- name: publish-pypi
  image: plugins/pypi
  settings:
    password:
      from_secret: pypi_password
    repository: https://upload.pypi.org/legacy/
    skip_build: true
    username:
      from_secret: pypi_username
  when:
    ref:
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: build-container-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.8
  commands:
  - python setup.py bdist_wheel
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: dryrun
  image: plugins/docker:18-linux-amd64
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish
  image: plugins/docker:18-linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: build-container-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: python:3.8
  commands:
  - python setup.py bdist_wheel
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: dryrun
  image: plugins/docker:18-linux-arm64
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish
  image: plugins/docker:18-linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: build-container-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: python:3.8
  commands:
  - python setup.py bdist_wheel
  environment:
    SETUPTOOLS_SCM_PRETEND_VERSION: ${DRONE_TAG##v}

- name: dryrun
  image: plugins/docker:18-linux-arm
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish
  image: plugins/docker:18-linux-arm
  settings:
    auto_tag: true
    auto_tag_suffix: arm
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: byrnedo/alpine-curl
  commands:
  - mkdir -p docs/themes/hugo-geekdoc/
  - curl -L https://github.com/xoxys/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C docs/themes/hugo-geekdoc/ --strip-components=1

- name: test
  image: klakegg/hugo:0.59.1-ext-alpine
  commands:
  - cd docs/ && hugo-official

- name: freeze
  image: appleboy/drone-ssh:1.5.5
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    script:
    - cp -R /var/www/virtual/geeklab/html/docker-tidy.geekdocs.de/ /var/www/virtual/geeklab/html/dockertidy_freeze/
    - ln -sfn /var/www/virtual/geeklab/html/dockertidy_freeze /var/www/virtual/geeklab/docker-tidy.geekdocs.de
    username:
      from_secret: ssh_username

- name: publish
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    rm: true
    source: docs/public/*
    strip_components: 2
    target: /var/www/virtual/geeklab/html/docker-tidy.geekdocs.de/
    username:
      from_secret: ssh_username

- name: cleanup
  image: appleboy/drone-ssh:1.5.5
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    script:
    - ln -sfn /var/www/virtual/geeklab/html/docker-tidy.geekdocs.de /var/www/virtual/geeklab/docker-tidy.geekdocs.de
    - rm -rf /var/www/virtual/geeklab/html/dockertidy_freeze/
    username:
      from_secret: ssh_username

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**

depends_on:
- build-package
- build-container-amd64
- build-container-arm64
- build-container-arm

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    username:
      from_secret: docker_username

- name: readme
  image: sheogorath/readme-to-dockerhub
  environment:
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPO_NAME: ${DRONE_REPO_NAME}
    DOCKERHUB_REPO_PREFIX: xoxys
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    README_PATH: README.md
    SHORT_DESCRIPTION: docker-tidy - Keep docker hosts tidy

- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- docs

---
kind: signature
hmac: 1a06f37400cd549c9b7f95b9395f0ba5c5bbb8f7069e8635b3761322d0fba07c

...
