FROM python:3.13-alpine@sha256:f66b117ec7379d205d7e67adc0ba5df1e4a1e98a7e17076b0e1075fde65feb04

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="docker-tidy"
LABEL org.opencontainers.image.url="https://docker-tidy.geekdocs.de/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/docker-tidy"
LABEL org.opencontainers.image.documentation="https://docker-tidy.geekdocs.de/"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/docker_tidy-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    apk --no-cache upgrade xz-libs sqlite-libs && \
    pip install --upgrade --no-cache-dir pip  && \
    pip install --no-cache-dir $(find / -name "docker_tidy-*.whl") && \
    apk del .build-deps && \
    rm -f docker_tidy-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/ && \
    rm -rf /tmp/*

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/docker-tidy", "gc"]
