FROM python:3.14-alpine@sha256:6f873e340e6786787a632c919ecfb1d2301eb33ccfbe9f0d0add16cbc0892116

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="docker-tidy"
LABEL org.opencontainers.image.url="https://docker-tidy.geekdocs.de/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/docker-tidy"
LABEL org.opencontainers.image.documentation="https://docker-tidy.geekdocs.de/"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/docker_tidy-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    apk --no-cache upgrade xz-libs sqlite-libs zlib && \
    pip install --upgrade --no-cache-dir pip  && \
    pip install --no-cache-dir $(find / -name "docker_tidy-*.whl") && \
    apk del .build-deps && \
    rm -f docker_tidy-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/ && \
    rm -rf /tmp/*

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/docker-tidy", "gc"]
