FROM arm64v8/python:3.9-alpine@sha256:132c64eae5e67bb06766eb5f470ce469245dafa7ed8de7af67d94d218e56731b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="docker-tidy"
LABEL org.opencontainers.image.url="https://docker-tidy.geekdocs.de/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/docker-tidy"
LABEL org.opencontainers.image.documentation="https://docker-tidy.geekdocs.de/"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/docker_tidy-*.whl /

RUN \
    apk --update add --virtual .build-deps gcc g++ && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "docker_tidy-*.whl") && \
    apk del .build-deps && \
    rm -f docker_tidy-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/ && \
    rm -rf /tmp/*

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/docker-tidy", "gc"]
