FROM python:3.11-alpine@sha256:ef8ab2f0859e5c68ae08df5ce9748c030b1c5989d728e34a0ef36a5a746a676c

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="docker-tidy"
LABEL org.opencontainers.image.url="https://docker-tidy.geekdocs.de/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/docker-tidy"
LABEL org.opencontainers.image.documentation="https://docker-tidy.geekdocs.de/"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/docker_tidy-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "docker_tidy-*.whl") && \
    apk del .build-deps && \
    rm -f docker_tidy-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/ && \
    rm -rf /tmp/*

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/docker-tidy", "gc"]
